# Generated by Django 2.2.1 on 2019-05-15 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='类别名称')),
                ('creater', models.IntegerField(verbose_name='创建人')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类列表',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='标签名称')),
                ('creater', models.IntegerField(verbose_name='创建人')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签列表',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('text', models.TextField(verbose_name='文章内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogCategory', verbose_name='种类')),
                ('tags', models.ManyToManyField(to='blog.BlogTag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客列表',
                'ordering': ('-id',),
            },
        ),
    ]
