# Generated by Django 2.2.1 on 2019-05-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='creater',
            field=models.IntegerField(default=-1, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='creater',
            field=models.IntegerField(default=-1, verbose_name='创建人'),
        ),
    ]
