# Generated by Django 2.2.1 on 2019-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190515_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='expire_to',
            field=models.DateTimeField(default='2019-01-01 00:00:00', verbose_name='过期不显示时间'),
        ),
    ]
