# Generated by Django 2.2.1 on 2019-05-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_expire_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-id',), 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('-id',), 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ('-id',), 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
