# Generated by Django 2.2.1 on 2019-05-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190516_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='creater',
        ),
        migrations.RenameField(
            model_name='blogcategory',
            old_name='creater',
            new_name='creater_id',
        ),
        migrations.RenameField(
            model_name='blogtag',
            old_name='creater',
            new_name='creater_id',
        ),
    ]
