# Generated by Django 2.2.1 on 2019-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190517_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='是否是 markdown'),
            preserve_default=False,
        ),
    ]
